package ch.hslu.enapp.webshop.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2018-12-04T09:17:20.216+01:00
 * Generated source version: 2.7.9
 * 
 */
@WebService(targetNamespace = "urn:microsoft-dynamics-schemas/page/item", name = "Item_Port")
@XmlSeeAlso({ObjectFactory.class})
public interface ItemPort {

    @WebMethod(operationName = "Update", action = "urn:microsoft-dynamics-schemas/page/item:Update")
    @RequestWrapper(localName = "Update", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "ch.hslu.enapp.webshop.wsdl.Update")
    @ResponseWrapper(localName = "Update_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "ch.hslu.enapp.webshop.wsdl.UpdateResult")
    public void update(
        @WebParam(mode = WebParam.Mode.INOUT, name = "Item", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
        javax.xml.ws.Holder<Item> item
    );

    @WebMethod(operationName = "IsUpdated", action = "urn:microsoft-dynamics-schemas/page/item:IsUpdated")
    @RequestWrapper(localName = "IsUpdated", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "ch.hslu.enapp.webshop.wsdl.IsUpdated")
    @ResponseWrapper(localName = "IsUpdated_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "ch.hslu.enapp.webshop.wsdl.IsUpdatedResult")
    @WebResult(name = "IsUpdated_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
    public boolean isUpdated(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
        java.lang.String key
    );

    @WebMethod(operationName = "Create", action = "urn:microsoft-dynamics-schemas/page/item:Create")
    @RequestWrapper(localName = "Create", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "ch.hslu.enapp.webshop.wsdl.Create")
    @ResponseWrapper(localName = "Create_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "ch.hslu.enapp.webshop.wsdl.CreateResult")
    public void create(
        @WebParam(mode = WebParam.Mode.INOUT, name = "Item", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
        javax.xml.ws.Holder<Item> item
    );

    @WebMethod(operationName = "ReadMultiple", action = "urn:microsoft-dynamics-schemas/page/item:ReadMultiple")
    @RequestWrapper(localName = "ReadMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "ch.hslu.enapp.webshop.wsdl.ReadMultiple")
    @ResponseWrapper(localName = "ReadMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "ch.hslu.enapp.webshop.wsdl.ReadMultipleResult")
    @WebResult(name = "ReadMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
    public ch.hslu.enapp.webshop.wsdl.ItemList readMultiple(
        @WebParam(name = "filter", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
        java.util.List<ch.hslu.enapp.webshop.wsdl.ItemFilter> filter,
        @WebParam(name = "bookmarkKey", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
        java.lang.String bookmarkKey,
        @WebParam(name = "setSize", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
        int setSize
    );

    @WebMethod(operationName = "UpdateMultiple", action = "urn:microsoft-dynamics-schemas/page/item:UpdateMultiple")
    @RequestWrapper(localName = "UpdateMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "ch.hslu.enapp.webshop.wsdl.UpdateMultiple")
    @ResponseWrapper(localName = "UpdateMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "ch.hslu.enapp.webshop.wsdl.UpdateMultipleResult")
    public void updateMultiple(
        @WebParam(mode = WebParam.Mode.INOUT, name = "Item_List", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
        javax.xml.ws.Holder<ItemList> itemList
    );

    @WebMethod(operationName = "Read", action = "urn:microsoft-dynamics-schemas/page/item:Read")
    @RequestWrapper(localName = "Read", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "ch.hslu.enapp.webshop.wsdl.Read")
    @ResponseWrapper(localName = "Read_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "ch.hslu.enapp.webshop.wsdl.ReadResult")
    @WebResult(name = "Item", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
    public ch.hslu.enapp.webshop.wsdl.Item read(
        @WebParam(name = "No", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
        java.lang.String no
    );

    @WebMethod(operationName = "CreateMultiple", action = "urn:microsoft-dynamics-schemas/page/item:CreateMultiple")
    @RequestWrapper(localName = "CreateMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "ch.hslu.enapp.webshop.wsdl.CreateMultiple")
    @ResponseWrapper(localName = "CreateMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "ch.hslu.enapp.webshop.wsdl.CreateMultipleResult")
    public void createMultiple(
        @WebParam(mode = WebParam.Mode.INOUT, name = "Item_List", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
        javax.xml.ws.Holder<ItemList> itemList
    );

    @WebMethod(operationName = "Delete", action = "urn:microsoft-dynamics-schemas/page/item:Delete")
    @RequestWrapper(localName = "Delete", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "ch.hslu.enapp.webshop.wsdl.Delete")
    @ResponseWrapper(localName = "Delete_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "ch.hslu.enapp.webshop.wsdl.DeleteResult")
    @WebResult(name = "Delete_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
    public boolean delete(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
        java.lang.String key
    );
}
